version: '3.1'

services:
  redmine:
    image: redmine
    depends_on:
      - db
    restart: always
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: password
      REDMINE_SECRET_KEY_BASE: supersecretkey
    labels:
      - traefik.enable=true
      - traefik.http.services.redmine.loadbalancer.server.port=3000
      - traefik.http.routers.redmine.entrypoints=web
      - "traefik.http.routers.redmine.rule=Host(`redmine.localhost`)"
      - traefik.http.routers.redmine.middlewares=cors
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"

    networks:
      - proxy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
    
    networks:
      - proxy

networks:
  proxy:
    name: proxy